import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  FlaskConical, Loader2, Trophy, ArrowRightLeft, BarChart3,
  CheckCircle2, Clock, Sparkles, X,
} from "lucide-react";
import { toast } from "sonner";

interface ABTest {
  id: string;
  product_id: string;
  status: string;
  winner_variant: string | null;
  started_at: string;
  test_duration_days: number;
  product?: { title: string; id: string };
}

interface Variant {
  id: string;
  variant_label: string;
  title: string;
  description: string;
  tags: any;
  seo_title: string;
  sales_count: number;
  revenue: number;
  is_active: boolean;
}

interface EvalResult {
  variants: Variant[];
  suggestedWinner: string | null;
  isExpired: boolean;
  daysRemaining: number;
}

interface Props {
  organizationId: string;
  userId: string;
  products: { id: string; title: string; shopify_product_id: number | null }[];
}

export const ABTestDashboard = ({ organizationId, userId, products }: Props) => {
  const [tests, setTests] = useState<ABTest[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState("");
  const [evalResults, setEvalResults] = useState<Record<string, EvalResult>>({});
  const [evaluatingId, setEvaluatingId] = useState<string | null>(null);
  const [actioningId, setActioningId] = useState<string | null>(null);

  useEffect(() => {
    loadTests();
  }, [organizationId]);

  const loadTests = async () => {
    setLoading(true);
    const { data } = await supabase
      .from("ab_tests")
      .select("*, product:products(id, title)")
      .eq("organization_id", organizationId)
      .order("created_at", { ascending: false });
    setTests((data as any) || []);
    setLoading(false);
  };

  const getAuthHeaders = async () => {
    const { data: { session } } = await supabase.auth.getSession();
    return session?.access_token
      ? { Authorization: `Bearer ${session.access_token}` }
      : undefined;
  };

  const handleCreate = async () => {
    if (!selectedProduct) {
      toast.error("Select a product first");
      return;
    }
    setCreating(true);
    try {
      const { data, error } = await supabase.functions.invoke("create-ab-test", {
        body: { productId: selectedProduct, organizationId },
        headers: await getAuthHeaders(),
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success("A/B test created! Variant B generated by AI.");
      setSelectedProduct("");
      await loadTests();
    } catch (err: any) {
      toast.error(err.message || "Failed to create test");
    } finally {
      setCreating(false);
    }
  };

  const handleEvaluate = async (testId: string) => {
    setEvaluatingId(testId);
    try {
      const { data, error } = await supabase.functions.invoke("manage-ab-test", {
        body: { testId, action: "evaluate" },
        headers: await getAuthHeaders(),
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setEvalResults((prev) => ({ ...prev, [testId]: data as EvalResult }));
    } catch (err: any) {
      toast.error(err.message || "Evaluation failed");
    } finally {
      setEvaluatingId(null);
    }
  };

  const handleSwap = async (testId: string) => {
    setActioningId(testId);
    try {
      const { data, error } = await supabase.functions.invoke("manage-ab-test", {
        body: { testId, action: "swap" },
        headers: await getAuthHeaders(),
      });
      if (error) throw error;
      toast.success("Variants swapped — update Shopify listing to apply");
      await handleEvaluate(testId);
    } catch (err: any) {
      toast.error(err.message || "Swap failed");
    } finally {
      setActioningId(null);
    }
  };

  const handleEnd = async (testId: string, winner: string) => {
    setActioningId(testId);
    try {
      const { data, error } = await supabase.functions.invoke("manage-ab-test", {
        body: { testId, action: "end", winnerVariant: winner },
        headers: await getAuthHeaders(),
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success(`Test ended — Variant ${winner} promoted as the listing`);
      await loadTests();
    } catch (err: any) {
      toast.error(err.message || "Failed to end test");
    } finally {
      setActioningId(null);
    }
  };

  const runningTests = tests.filter((t) => t.status === "running");
  const completedTests = tests.filter((t) => t.status === "completed");
  const shopifyProducts = products.filter((p) => p.shopify_product_id);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-semibold flex items-center gap-2">
            <FlaskConical className="h-4 w-4 text-primary" />
            A/B Listing Tests
          </h3>
          <p className="text-xs text-muted-foreground">
            Generate challenger listings and track which variant sells better
          </p>
        </div>
      </div>

      {/* Create new test */}
      <div className="flex items-center gap-2 rounded-lg border border-dashed border-border bg-card/50 p-3">
        <select
          value={selectedProduct}
          onChange={(e) => setSelectedProduct(e.target.value)}
          className="flex-1 rounded-md border border-input bg-background px-3 py-1.5 text-sm"
        >
          <option value="">Select a Shopify product…</option>
          {shopifyProducts.map((p) => (
            <option key={p.id} value={p.id}>{p.title}</option>
          ))}
        </select>
        <Button
          size="sm"
          onClick={handleCreate}
          disabled={creating || !selectedProduct}
          className="gap-1.5"
        >
          {creating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Sparkles className="h-3.5 w-3.5" />
          )}
          Start A/B Test
        </Button>
      </div>

      {loading ? (
        <div className="flex justify-center py-6">
          <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
        </div>
      ) : runningTests.length === 0 && completedTests.length === 0 ? (
        <div className="rounded-lg border border-dashed border-border bg-card/50 p-6 text-center">
          <FlaskConical className="mx-auto h-8 w-8 text-muted-foreground mb-2" />
          <p className="text-sm font-medium">No A/B tests yet</p>
          <p className="text-xs text-muted-foreground mt-1">
            Select a product above and start your first listing experiment
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {runningTests.map((test) => {
            const eval_ = evalResults[test.id];
            return (
              <Card key={test.id} className="p-4 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="bg-primary/10 text-primary">
                      <Clock className="h-3 w-3 mr-1" /> Running
                    </Badge>
                    <span className="text-sm font-medium">{test.product?.title || "Product"}</span>
                  </div>
                  <div className="flex gap-1">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleEvaluate(test.id)}
                      disabled={evaluatingId === test.id}
                      className="gap-1.5"
                    >
                      {evaluatingId === test.id ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <BarChart3 className="h-3.5 w-3.5" />
                      )}
                      Check Results
                    </Button>
                  </div>
                </div>

                {eval_ && (
                  <div className="space-y-2">
                    <div className="grid grid-cols-2 gap-2">
                      {eval_.variants.map((v) => (
                        <div
                          key={v.id}
                          className={`rounded-lg border p-3 space-y-1 ${
                            v.is_active ? "border-primary bg-primary/5" : "border-border"
                          }`}
                        >
                          <div className="flex items-center justify-between">
                            <span className="text-xs font-bold">
                              Variant {v.variant_label}
                              {v.is_active && (
                                <Badge variant="secondary" className="ml-1.5 text-[10px] bg-primary/10 text-primary">
                                  Active
                                </Badge>
                              )}
                            </span>
                            {eval_.suggestedWinner === v.variant_label && eval_.isExpired && (
                              <Trophy className="h-3.5 w-3.5 text-amber-500" />
                            )}
                          </div>
                          <p className="text-xs truncate text-muted-foreground">{v.title}</p>
                          <div className="flex gap-3 text-xs">
                            <span>{v.sales_count} sales</span>
                            <span className="font-medium">${v.revenue.toFixed(2)}</span>
                          </div>
                        </div>
                      ))}
                    </div>

                    <div className="flex items-center justify-between">
                      <p className="text-xs text-muted-foreground">
                        {eval_.isExpired
                          ? `Test complete — suggested winner: Variant ${eval_.suggestedWinner}`
                          : `${eval_.daysRemaining} day${eval_.daysRemaining !== 1 ? "s" : ""} remaining`}
                      </p>
                      <div className="flex gap-1">
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleSwap(test.id)}
                          disabled={actioningId === test.id}
                          className="gap-1"
                        >
                          <ArrowRightLeft className="h-3 w-3" />
                          Swap
                        </Button>
                        {eval_.variants.map((v) => (
                          <Button
                            key={v.id}
                            size="sm"
                            variant={eval_.suggestedWinner === v.variant_label ? "default" : "outline"}
                            onClick={() => handleEnd(test.id, v.variant_label)}
                            disabled={actioningId === test.id}
                            className="gap-1"
                          >
                            <Trophy className="h-3 w-3" />
                            Pick {v.variant_label}
                          </Button>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </Card>
            );
          })}

          {completedTests.length > 0 && (
            <div className="space-y-2">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Completed</p>
              {completedTests.slice(0, 5).map((test) => (
                <div
                  key={test.id}
                  className="flex items-center gap-3 rounded-lg border border-border bg-card/50 px-4 py-2.5"
                >
                  <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
                  <span className="text-sm flex-1 truncate">{test.product?.title}</span>
                  <Badge variant="secondary" className="shrink-0">
                    Winner: {test.winner_variant}
                  </Badge>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
